#ifndef CONFIG_H
#define CONFIG_H

typedef enum {WHOLE, HALF, QUARTER, EIGHTH, SIXTEENTH, WHOLE_POINT, HALF_POINT, QUARTER_POINT, EIGHTH_POINT, SIXTEENTH_POINT, THIRTYSECOND, THIRTYSECOND_POINT} LENGTH;
typedef enum {SILENCE, DO, DO_D, RE, RE_D, MI, FA, FA_D, SOL, SOL_D, LA, LA_D, SI} TYPE_NOTE;
#define LA_REF 440
#define OCTAVE_REF 3

#endif // CONFIG_H
